#!/bin/bash

TGT="./zfs-chroot"
export TGT

if [ -d "$TGT" ] ; then
	        umount -f $TGT/proc
		        umount -f $TGT/sys
			        rm -rf $TGT
fi

# Make sure the truenas target exists
ln -fs /usr/share/debootstrap/scripts/bullseye /usr/share/debootstrap/scripts/truenas

# Bootstrap the zfs chroot
debootstrap truenas $TGT file:///srv/aptly-publish/truenas/unstable

# Make the chroot ready to build
mount proc $TGT/proc -t proc
mount sysfs $TGT/sys -t sysfs
cp /etc/hosts $TGT/etc/hosts

# Setup the apt repo
echo "deb http://apt.tn.ixsystems.com/truenas/unstable/ truenas main" > ${TGT}/etc/apt/sources.list

chroot ${TGT} apt update
if [ $? -ne 0 ] ; then
	   exit 1
fi

chroot ${TGT} apt install -y locales
if [ $? -ne 0 ] ; then
	   exit 1
fi
chroot ${TGT} apt install -y linux-image-amd64
if [ $? -ne 0 ] ; then
	   exit 1
fi
chroot ${TGT} apt install -y debhelper
if [ $? -ne 0 ] ; then
	   exit 1
fi

# Build the .deb package now
cp scripts/build-zfs-deb ${TGT}/build.sh
chmod 755 ${TGT}/build.sh

chroot ${TGT} sh /build.sh
if [ $? -ne 0 ] ; then
	   exit 1
fi
