#!/bin/bash

APTLY="aptly -config $(pwd)/conf/aptly.conf"
 
update_mirror() {
	DIST="$1"
	MIRROR="$2"
	BUILD="$3"
	REPO="$4"

	# Cleanup old published / snapshots
	${APTLY} publish drop ${DIST} filesystem:truenas:truenas/${BUILD}
	${APTLY} snapshot drop ${MIRROR}-current

	# Check if we need to init the mirror
	${APTLY} mirror list | grep -q -w ${MIRROR}
	if [ $? -ne 0 ] ; then
		${APTLY} mirror create ${MIRROR} ${REPO} ${DIST}
	fi

	# Update the mirror from upstream
	${APTLY} mirror update ${MIRROR}

	# Create -current snapshot
	${APTLY} snapshot create ${MIRROR}-current from mirror ${MIRROR}

	# Publish the mirror
	${APTLY} publish snapshot -gpg-key=${GPGKEY} ${MIRROR}-current filesystem:truenas:truenas/${BUILD}

}

check_keyring() {
	# Ensure all the debian keys are installed
	gpg1 --list-keys --keyring trustedkeys.gpg >/dev/null 2>/dev/null
	if [ $? -ne 0 ] ; then
		gpg1 --no-default-keyring --keyring trustedkeys.gpg --import /usr/share/keyrings/debian-archive-keyring.gpg
	fi

	# Make sure TrueNAS key is installed
	gpg1 --list-keys --keyring trustedkeys.gpg | grep -q ixsystems
	if [ $? -ne 0 ] ; then
		gpg1 --no-default-keyring --keyring trustedkeys.gpg --import conf/truenas.key
	fi


}

# Ensure debmirror is installed
which aptly >/dev/null 2>/dev/null
if [ $? -ne 0 ] ; then
	echo "Missing 'aptly' utilty, please install with 'apt install aptly'"
	exit 1
fi

# Ensure that debian-keyring is installed
if [ ! -e "/usr/share/keyrings/debian-archive-keyring.gpg" ] ; then
	echo "Missing debian-keyring, please install with 'apt install debian-keyring'"
	exit 1
fi

case $1 in
	debian) 
		update_mirror "${DEBDIST}" "${DEBAPTLYMIRROR}" "${TRUENASBUILD}" "${DEBREPO}"
		;;
	truenas) 
		update_mirror "${TNDIST}" "${TNAPTLTMIRROR}" "${TRUENASBUILD}" "${TNREPO}"
		;;

	*)
		echo "Invalid argument $1"
		exit 1
		;;
esac
