#!/bin/bash

APTLY="aptly -config $(pwd)/conf/aptly.conf"
 
update_mirror() {
	REPO="truenas-unstable"
        PREFIX="unstable/truenas"
	UPLOADDIR="/home/pkgupload/repo"

	# Cleanup old published / snapshots
	${APTLY} publish drop truenas filesystem:truenas:${PREFIX}
	${APTLY} snapshot drop ${REPO}-snapshot

	# Check if we need to init the mirror
	${APTLY} repo list | grep -q -w "\[${REPO}\]"
	if [ $? -ne 0 ] ; then
		${APTLY} repo create ${REPO}
		if [ $? -ne 0 ] ; then exit 1; fi
	fi

	# Update the mirror from upstream
	${APTLY} repo add -remove-files -force-replace ${REPO} ${UPLOADDIR}
	if [ $? -ne 0 ] ; then exit 1; fi

	# Create -snapshot snapshot
	${APTLY} snapshot create ${REPO}-snapshot from repo ${REPO}
	if [ $? -ne 0 ] ; then exit 1; fi

	# Publish the mirror
	${APTLY} publish snapshot -distribution="truenas" -gpg-key=${GPGKEY} ${REPO}-snapshot filesystem:truenas:${PREFIX}
	if [ $? -ne 0 ] ; then exit 1; fi

}

check_keyring() {
	# Ensure all the debian keys are installed
	gpg1 --list-keys --keyring trustedkeys.gpg >/dev/null 2>/dev/null
	if [ $? -ne 0 ] ; then
		gpg1 --no-default-keyring --keyring trustedkeys.gpg --import /usr/share/keyrings/debian-archive-keyring.gpg
	fi

	# Make sure TrueNAS key is installed
	gpg1 --list-keys --keyring trustedkeys.gpg | grep -q ixsystems
	if [ $? -ne 0 ] ; then
		gpg1 --no-default-keyring --keyring trustedkeys.gpg --import conf/truenas.key
	fi
}

# Ensure debmirror is installed
which aptly >/dev/null 2>/dev/null
if [ $? -ne 0 ] ; then
	echo "Missing 'aptly' utilty, please install with 'apt install aptly'"
	exit 1
fi

# Ensure that debian-keyring is installed
if [ ! -e "/usr/share/keyrings/debian-archive-keyring.gpg" ] ; then
	echo "Missing debian-keyring, please install with 'apt install debian-keyring'"
	exit 1
fi

update_mirror
