#!/bin/bash

APTLY="aptly -config $(pwd)/conf/aptly.conf"
 
update_truenas() {

	# Cleanup old published / snapshots
	${APTLY} publish drop ${TNDIST} filesystem:truenas:truenas/${TRUENASBUILD}
	${APTLY} snapshot drop ${TNAPTLYMIRROR}-current

	# Check if we need to init the mirror
	${APTLY} mirror list | grep -q -w ${TNAPTLYMIRROR}
	if [ $? -ne 0 ] ; then
		${APTLY} mirror create ${TNAPTLYMIRROR} ${TNREPO} ${TNDIST}
	fi

	# Update the mirror from upstream
	${APTLY} mirror update ${TNAPTLYMIRROR}

	# Create -current snapshot
	${APTLY} snapshot create ${TNAPTLYMIRROR}-current from mirror ${TNAPTLYMIRROR}

	# Publish the mirror
	${APTLY} publish snapshot -gpg-key=${GPGKEY} ${TNAPTLYMIRROR}-current filesystem:truenas:truenas/${TRUENASBUILD}

}

update_debian() {
 
	# Debian version(s) to mirror
	DIST=${DEBDIST}
 
	# architecture
	ARCH=amd64
 
	# Check if we need to init the mirror
	${APTLY} mirror list | grep -q -w ${DEBAPTLYMIRROR}
	if [ $? -ne 0 ] ; then
		${APTLY} mirror create -with-udebs -with-sources ${DEBAPTLYMIRROR} ${DEBREPO} ${DEBDIST}
	fi

	# log timestamp
	logger -t mirror[$$] updating Debian mirror
 
	${APTLY} mirror update ${DEPAPTLYMIRROR}

	logger -t mirror[$$] finished updating Debian mirror
}

check_keyring() {
	# Ensure all the debian keys are installed
	gpg1 --list-keys --keyring trustedkeys.gpg >/dev/null 2>/dev/null
	if [ $? -ne 0 ] ; then
		gpg1 --no-default-keyring --keyring trustedkeys.gpg --import /usr/share/keyrings/debian-archive-keyring.gpg
	fi

	# Make sure TrueNAS key is installed
	gpg1 --list-keys --keyring trustedkeys.gpg | grep -q ixsystems
	if [ $? -ne 0 ] ; then
		gpg1 --no-default-keyring --keyring trustedkeys.gpg --import conf/truenas.key
	fi


}

# Ensure debmirror is installed
which aptly >/dev/null 2>/dev/null
if [ $? -ne 0 ] ; then
	echo "Missing 'aptly' utilty, please install with 'apt install aptly'"
	exit 1
fi

# Ensure that debian-keyring is installed
if [ ! -e "/usr/share/keyrings/debian-archive-keyring.gpg" ] ; then
	echo "Missing debian-keyring, please install with 'apt install debian-keyring'"
	exit 1
fi

case $1 in
	debian) 
		update_debian
		;;
	truenas) 
		update_truenas
		;;

	*)
		echo "Invalid argument $1"
		exit 1
		;;
esac
